#!/usr/bin/env bash

grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | cut -d':' -f1 | sed 's/label/input/' | xargs cat

# Following script outputs current cpu die temperature in milidegree-celcius, convert it to celcius and fahrenheit and display as:
#
# Celcius: 42.0 C
# Fahrenheit: 107.6 F

mc=$(grep -E 'Tctl|Tdie|Package id' /sys/class/hwmon/hwmon*/temp*_label | head -n1 | cut -d':' -f1 | sed 's/label/input/' | xargs cat)

Celsius=$(bc <<< "scale=1; $mc / 1000")

Fahrenheit=$(bc <<< "scale=1; ($Celsius * 9/5) + 32")

echo "Celsius: $Celsius °C"
echo "Fahrenheit: $Fahrenheit °F"
