#!/usr/bin/env bash

require() {
    command -v "$1" &>/dev/null || { echo "$1 is not installed"; exit 1; }
}

require find
require grep

declare -A special_cases=(
    ["tar.gz"]="tar"
    ["pdf"]="documents"
    ["doc"]="documents"
    ["docx"]="documents"
    ["mp3"]="music"
    ["mp4"]="videos"
    ["mkv"]="videos"
    ["jpg"]="images"
    ["jpeg"]="images"
    ["png"]="images"
)

find . -type f -maxdepth 1 | while read -r file; do
    ext="${file##*.}"
    folder="${special_cases[$ext]:-$ext}"

    mkdir -p "$folder"
    mv "$file" "$folder"
done

echo "Files are organized accordingly"


