#!/usr/bin/env bash

generate_password() {
    local length="$1"

    if [[ ! "$length" =~ ^[0-9]+$ ]] || [[ "$length" -le 0 ]]; then
        echo "Error: Please provide a valid positive number for password length."
        return 1;
    fi

}

generate_password 12
