#!/usr/bin/env bash

find . -name .git -type d -prune | while read -r git_dir; do
    repo_dir=$(dirname "$git_dir")
    echo "Cleaning: $repo_dir"

    if [[ -f "$repo_dir/.gitignore" ]]; then
        (cd "$repo_dir" && git rm -r --cached -q -f -X '*' && git clean -fdX)
    else
        echo "No .gitignore found in $repo_dir"
    fi
done

echo "Cleanup complete!"

