#!/usr/bin/env bash

# Extract the wifi username (SSID)
# Refer: "iw dev wlan0 link" command output for this

ssid=$(iw dev wlan0 link | awk -F ': ' '/SSID/ {print $2}')

if [[ -n "$ssid" ]]; then
    echo "$ssid , Connected,secured"
else
    echo "Not connected"
fi
